In [ ]:
import numpy as np

##Creating Arrays in Numpy

In [3]:
import numpy as np

arr_1D = np.array([1,2,3,4,5])
print("1D array:", arr_1D)

arr_2D = np.array([[1,2,3,4,4],[5,6,7,8,9]])
print("2D Array:", arr_2D)

1D array: [1 2 3 4 5]
2D Array: [[1 2 3 4 4]
 [5 6 7 8 9]]


In [6]:
#Comparison between  numpy array and list  why numpy array is fasrer then  numpy list 

import time
start = time.time()
np_list = [i*2 for i in range(100000)]
print("\n List operation time: " , time.time() - start )

# NUMPY ARRAY
start = time.time()

np_array = np.arange(0 ,100000)*2
print("\n Array operation time: " , time.time() - start )




 List operation time:  0.004465579986572266

 Array operation time:  0.0008025169372558594


CREATING ARRAS OF ALL TYPE IN NUMPY


In [9]:
np_Zeros = np.zeros((3,4))
print("Zeros Array\n" , np_Zeros)

np_ones = np.ones((2,3)) 
print("Ones Array\n" , np_ones)

full = np.full((2,2),7)
print("Full Array\n" , full)

random = np.random.random((2,3))
print("Random Array\n" , random)

sequence = np.arange(0,12,2)
print("Sequence Array\n" , sequence)



Zeros Array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array
 [[7 7]
 [7 7]]
Random Array
 [[0.96459236 0.55150994 0.8469212 ]
 [0.96583941 0.08722043 0.01655366]]
Sequence Array
 [ 0  2  4  6  8 10]


VECTOR  MATRIX AND TENSOR 


In [14]:
Vector = np.array([1,2,3,4])
print("Vector" , Vector)

Matrix = np.array([[1,2,3,4],
                  [2,4,5,6]])
print("Matrix" , Matrix)

tensor = np.array([
    [
        [[1,2,3],[2,6,7]],
        [[1,2,4],[7,8,9]]
    ]
])
print("Tensor", tensor)

Vector [1 2 3 4]
Matrix [[1 2 3 4]
 [2 4 5 6]]
Tensor [[[[1 2 3]
   [2 6 7]]

  [[1 2 4]
   [7 8 9]]]]


## ARRAY PROPERTIES

In [17]:
arr = np.array([[1,2,3,4]
                ,[5,6,7,9]])
print("Shape " ,arr.shape)
print("Dimension ", arr.ndim)

Shape  (2, 4)
Dimension  2
